version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'employee'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      # - my-db:/var/lib/mysql
      # - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql